/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Dimension;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author NyKo
 */
public class Suppression extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;
    private Suppression fenConfirmationSuppression;

    /**
     * Creates new form Suppression
     */
    public Suppression(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Suppression du compte");
        this.setLocationRelativeTo(parent);
        
        Dimension size = new Dimension (510,400);
        this.setSize(size);
        this.setMinimumSize(size);
        this.setMaximumSize(size);
        this.setPreferredSize(size);
 
        this.setModal(true);

        this.fenetre = (InterfaceGraphique) parent;
        this.jLabelConfirmationDeSuppression.setVisible(false);
        this.jLabelCID.setVisible(false);
        this.jLabelCMdp.setVisible(false);
        this.jTextFieldIdentifiant.setVisible(false);
        this.jPassConfirmMdp.setVisible(false);
        this.jButtonCOk.setVisible(false);
        
        Color couleurDeFond = new Color(226, 225, 235);
        this.setBackground(couleurDeFond);
        
     


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConfirmationSupprimerTexte = new javax.swing.JLabel();
        jButtonConfirmeSuppressionOui = new javax.swing.JButton();
        jButtonConfirmeSuppressionNon = new javax.swing.JButton();
        jLabelConfirmationDeSuppression = new javax.swing.JLabel();
        jLabelCID = new javax.swing.JLabel();
        jLabelCMdp = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jButtonCOk = new javax.swing.JButton();
        jPassConfirmMdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(510, 340));
        setMinimumSize(new java.awt.Dimension(510, 340));
        setPreferredSize(new java.awt.Dimension(510, 340));

        jLabelConfirmationSupprimerTexte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelConfirmationSupprimerTexte.setText("Etes-vous sûr de vouloir supprimer votre compte ?");

        jButtonConfirmeSuppressionOui.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonConfirmeSuppressionOui.setText("Oui");
        jButtonConfirmeSuppressionOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmeSuppressionOuiActionPerformed(evt);
            }
        });

        jButtonConfirmeSuppressionNon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonConfirmeSuppressionNon.setText("Non");
        jButtonConfirmeSuppressionNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmeSuppressionNonActionPerformed(evt);
            }
        });

        jLabelConfirmationDeSuppression.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelConfirmationDeSuppression.setText("Veuillez rentrer votre identifiant pour supprimer votre compte définitivement.");

        jLabelCID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCID.setText("Identifiant");

        jLabelCMdp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCMdp.setText("Mot de passe");

        jButtonCOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCOk.setText("Ok");
        jButtonCOk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOkActionPerformed(evt);
            }
        });

        jPassConfirmMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassConfirmMdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelConfirmationSupprimerTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButtonConfirmeSuppressionOui, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButtonConfirmeSuppressionNon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelConfirmationDeSuppression))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabelCID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCMdp)
                            .addComponent(jPassConfirmMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addComponent(jButtonCOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelConfirmationSupprimerTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmeSuppressionNon)
                    .addComponent(jButtonConfirmeSuppressionOui))
                .addGap(73, 73, 73)
                .addComponent(jLabelConfirmationDeSuppression)
                .addGap(15, 15, 15)
                .addComponent(jLabelCID)
                .addGap(3, 3, 3)
                .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCMdp)
                        .addGap(3, 3, 3)
                        .addComponent(jPassConfirmMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmeSuppressionNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmeSuppressionNonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jButtonConfirmeSuppressionNonActionPerformed

    private void jButtonConfirmeSuppressionOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmeSuppressionOuiActionPerformed
        // TODO add your handling code here:

        this.jLabelConfirmationDeSuppression.setVisible(true);
        this.jLabelCID.setVisible(true);
        this.jLabelCMdp.setVisible(true);
        this.jTextFieldIdentifiant.setVisible(true);
        this.jPassConfirmMdp.setVisible(true);
        this.jButtonCOk.setVisible(true);


    }//GEN-LAST:event_jButtonConfirmeSuppressionOuiActionPerformed

    private void jButtonCOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOkActionPerformed
        // TODO add your handling code here:
        if (jTextFieldIdentifiant.getText().length()==0 || jPassConfirmMdp.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Erreur de saisie, les deux champs doivent être renseignés.");
            
        } else if(jTextFieldIdentifiant.getText().compareTo(this.fenetre.getIdentifiant()) != 0) {
            JOptionPane.showMessageDialog(this, "Votre identifiant est " + this.fenetre.getIdentifiant() + " et vous avez tapez " +"'"+this.jTextFieldIdentifiant.getText()+"'");
        }else{
            
            try {
                //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                //instanciation de la classe Driver du paquetage jdbc de mysql
                Class.forName("com.mysql.jdbc.Driver");
                //Chaine de connexion (prise dans l'onglet services)
                String connexionUrl="jdbc:mysql://localhost:3306/applietudiants?user=applietudiants&password=sio";
               
                //etablissement de la connexion
                Connection maConnexion=(Connection)DriverManager.getConnection(connexionUrl);
                
                //requete
                Statement requete=maConnexion.createStatement();
                String identifiant=jTextFieldIdentifiant.getText();
                String mdp=jPassConfirmMdp.getText();
                
            
                //application du cryptage md5 au mdp
                // ici on appelle md5 membre static de la classe outils
                mdp=Outils.md5(mdp);
            
                ResultSet lignesRetournees=requete.executeQuery("select * from Utilisateurs where identifiant='"+identifiant+"' and mot_de_passe='"+mdp+"'");
                if (lignesRetournees.next()){
                    
                    requete.executeUpdate("DELETE FROM Utilisateurs WHERE identifiant = '"+identifiant+"' AND mot_de_passe = '"+mdp+"'");
                    requete.executeUpdate("DELETE FROM cv_experience_professionnelle WHERE identifiant = '"+identifiant+"' ");
                    requete.executeUpdate("DELETE FROM cv_formation WHERE identifiant = '"+identifiant+"' ");
                    requete.executeUpdate("DELETE FROM cv_informatique WHERE identifiant = '"+identifiant+"' ");
                    requete.executeUpdate("DELETE FROM cv_langues WHERE identifiant ='"+identifiant+"' ");
                    requete.executeUpdate("DELETE FROM cv_centres_dinteret WHERE identifiant= '"+identifiant+"' ");
                    requete.executeUpdate("DELETE FROM cv_titre WHERE identifiant = '"+identifiant+"'");
                          
                     
                    this.fenetre.deconnecte();
                    
                     this.fenetre.getPanelPrincipal().setVisible(false);
                      this.fenetre.majConnexion();
                     this.fenetre.CreationInscriptionConnexion();
                    this.setVisible(false);  
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Identifiant ou mot de passe incorrect");
                }
                
                
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..."+ex.toString());
            }
             catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "SQL exception ... "+ex.toString());
            }
            catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    
    }//GEN-LAST:event_jButtonCOkActionPerformed

    private void jPassConfirmMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassConfirmMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassConfirmMdpActionPerformed
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suppression.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suppression.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suppression.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suppression.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Suppression dialog = new Suppression(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//        public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCOk;
    private javax.swing.JButton jButtonConfirmeSuppressionNon;
    private javax.swing.JButton jButtonConfirmeSuppressionOui;
    private javax.swing.JLabel jLabelCID;
    private javax.swing.JLabel jLabelCMdp;
    private javax.swing.JLabel jLabelConfirmationDeSuppression;
    private javax.swing.JLabel jLabelConfirmationSupprimerTexte;
    private javax.swing.JPasswordField jPassConfirmMdp;
    private javax.swing.JTextField jTextFieldIdentifiant;
    // End of variables declaration//GEN-END:variables
}
